### DISCUSSION TITLE
Unresolved actions

### DISCUSSION THREAD

**Discussion by depau** [dsoftwareinc/ghactions-manager#165] [Q&A]
I noticed that external actions (for instance `JetBrains/qodana-action@v2024.1`) get stuck forever saying they're unresolved:

```
Unresolved [JetBrains/qodana-action@v2024.1] - you may need to connect your GitHub
```

My GitHub account is connected and I tried to switch to a PAT as well, with no change.

Am I missing something?

Here's a workflow file that isn't working:

```yml
---
# Reusable workflow for running Qodana code analysis
name: Qodana
on:
  workflow_call:
jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }} # to check out the actual pull request commit, not the merge commit
        fetch-depth: 0 # a full history is required for pull request analysis

    - name: 'Qodana Scan'
      uses: JetBrains/qodana-action@v2024.1
      env:
        QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
```
