### ISSUE TITLE
Prevent dispatching a workflow without manual dispatch

### ISSUE THREAD

**Issue by cunla** [dsoftwareinc/ghactions-manager#172]
Currently all workflows are listed in workflow dispatch menu.
Disable workflows if they can't be manually dispatched

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/172">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/172/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/172/pledge.svg">
</picture>
</a>

**Comment by sbennett-ihasco** [comment]
Hi,

This change has disabled workflows which I was previously able to dispatch using the plugin. What do I need to change in my workflow to allow this?

Here's my workflow event config. The `release-type` input has a default, which I thought would allow manual dispatch?

```yml
on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        required: true
        description: Release Type
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
```

A very useful plugin! Thanks!
