### ISSUE TITLE
Cannot Manually Dispatch Workflow with Default Inputs

### ISSUE THREAD

**Issue by sbennett-ihasco** [dsoftwareinc/ghactions-manager#176]
### Describe the bug

Cannot manually dispatch workflows even with input defaults

**Describe the bug:**

It should be possible to manually dispatch a workflow with the following event trigger configuration: as its `release-type` input has a default ("patch").

```yaml
on:
  workflow_dispatch:
    inputs:
      release-type:
        type: choice
        required: true
        description: Release Type
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'
```

### Steps to reproduce

- Attempt to manually dispatch a workflow with an event trigger configured as above with (a) default input(s)
- The plugin does not allow manual dispatch

### Expected behavior

- Attempt to manually dispatch a workflow with an event trigger configured as above with (a) default input(s)
- The plugin allows manual dispatch of workflows with event triggers with default input values

### Additional context

Plugin version: 2024.2.5
IDE: PhpStorm 2024.1.4
OS: Debian GNU/Linux 12 (bookworm)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/176">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/176/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/176/pledge.svg">
</picture>
</a>
