### ISSUE TITLE
Inspection highlights imported action as unknown

### ISSUE THREAD

**Issue by olmoser** [dsoftwareinc/ghactions-manager#192]
### Describe the bug
When I import a local Github Action workflow file via `uses: ./workflow.yml`, inspection highlights the imported local workflow as unknown.

### Steps to reproduce
Create a Github Action and reference a reusable workflow via uses:

```
---
name: deploy cloud function DEV

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    uses: ./.github/workflows/create-pr.yml
    secrets: inherit
    with:
      branch: test
      environment: dev
```

See the IDE highlight the import as error:

![image](https://github.com/user-attachments/assets/bba3af9b-621b-410f-b888-81c7b09ae941)

I also tried to reference the workflow file in the current directory (`./create-pr.yml`) and via the repository (`myorg/platform-infrastructure/.github/workflows/create-pr.yml`), still the same error.

Here is the settings of the plugin:

<img width="736" alt="image" src="https://github.com/user-attachments/assets/e752865c-7d7d-4e3c-80ac-c4d547756a77">

### Expected behavior

There is no inspection error and you can navigate to the reusable workflow

### Additional context

Plugin version: 2024.2.13
IDE: Goland 2024.2.3
OS: Sequoia 15.1

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/dsoftwareinc) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/dsoftwareinc/ghactions-manager/issues/192">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/192/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/dsoftwareinc/ghactions-manager/issues/192/pledge.svg">
</picture>
</a>
